verifyDepsBeforeRun: install
minimumReleaseAge: 1440
allowBuilds:
  "@firebase/util": true
  "@parcel/watcher": false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  protobufjs: false
overrides:
  "@angular/common": "^21.2.15"
  "@angular/core": "^21.2.15"
  "@angular/platform-browser": "^21.2.15"
  "@angular/platform-browser-dynamic": "^21.2.15"
  undici: "^7.24.4"
  glob: "^13.0.6"
  rimraf: "^6.1.3"
  inflight: "^1.0.6"
