verifyDepsBeforeRun: install
minimumReleaseAge: 1440
update:
  githubActions: true
allowBuilds:
  "@firebase/util": true
  "@parcel/watcher": false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  protobufjs: false
overrides:
  "@angular/common": "^22.1.5"
  "@angular/core": "^22.1.5"
  "@angular/platform-browser": "^22.1.5"
  immutable: ^5.1.8
peerDependencyRules:
  allowedVersions:
    "@angular/compiler": "22"
patchedDependencies:
  "@angular/fire@20.0.1": patches/@angular__fire@20.0.1.patch
