name: Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Setup environment
        run: |
          echo "export const environment = { production: false };" > src/environments/environment.dev.ts
          echo -n "export const environment = " > src/environments/environment.prod.ts
          echo "${{ secrets.FIREBASE_CONFIG }}" | base64 -d >> src/environments/environment.prod.ts

      - name: Build
        run: pnpm release

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAANVANKEMPEN_F242D }}"
          projectId: daanvankempen-f242d
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
